import requests
import json
from typing import Optional, List, Dict, Any
from ..config import get_settings

settings = get_settings()

class LLMService:
    def __init__(self):
        self.openrouter_key = settings.OPENROUTER_API_KEY
        self.gemini_key = settings.GEMINI_API_KEY
        self.openrouter_url = "https://openrouter.ai/api/v1/chat/completions"
        self.gemini_url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key={self.gemini_key}"
        self.model_id = "openai/gpt-oss-120b:free"
        self._call_count = 0
        self.llm_mode = (settings.LLM_MODE or "auto").strip().lower()
        if self.llm_mode not in {"auto", "online", "offline"}:
            self.llm_mode = "auto"

    def get_mode(self) -> str:
        return self.llm_mode

    def set_mode(self, mode: str) -> str:
        normalized = (mode or "auto").strip().lower()
        if normalized not in {"auto", "online", "offline"}:
            normalized = "auto"
        self.llm_mode = normalized
        settings.LLM_MODE = normalized
        return self.llm_mode

    async def generate_with_reasoning(self, messages: List[Dict[str, Any]], mode: str = "auto") -> Dict[str, Any]:
        """
        Generates a response using alternating LLMs (Gemini/OpenRouter).
        mode: 'auto' (alternate), 'gemini', or 'openrouter'
        """
        if self.llm_mode == "offline":
            return self._offline_response(messages)

        self._call_count += 1
        
        # Decide which LLM to use
        use_gemini = False
        if mode == "gemini":
            use_gemini = True
        elif mode == "openrouter":
            use_gemini = False
        else:
            use_gemini = self._call_count % 2 == 0
            
        if use_gemini and self.gemini_key:
            return await self._generate_gemini(messages)
        else:
            return await self._generate_openrouter(messages)

    async def _generate_gemini(self, messages: List[Dict[str, Any]]) -> Dict[str, Any]:
        prompt = messages[-1]["content"] if messages else "guidance"
        data = {
            "contents": [{"parts": [{"text": prompt}]}]
        }
        try:
            response = requests.post(self.gemini_url, json=data, timeout=10)
            response.raise_for_status()
            res_json = response.json()
            content = res_json['candidates'][0]['content']['parts'][0]['text']
            return {
                "content": content,
                "reasoning_details": "Response generated by Google Gemini Pro. Dynamic benefit analysis complete."
            }
        except Exception as e:
            return self._get_fallback(f"Gemini Error: {e}")

    async def _generate_openrouter(self, messages: List[Dict[str, Any]]) -> Dict[str, Any]:
        if not self.openrouter_key:
            return self._get_fallback("OpenRouter key missing")

        headers = {
            "Authorization": f"Bearer {self.openrouter_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://bharat-benefits.navigator",
            "X-Title": "Bharat Benefits Navigator"
        }
        data = {
            "model": self.model_id,
            "messages": messages,
            "reasoning": {"enabled": True}
        }
        try:
            response = requests.post(self.openrouter_url, headers=headers, data=json.dumps(data), timeout=10)
            response.raise_for_status()
            res_json = response.json()
            message = res_json['choices'][0]['message']
            return {
                "content": message.get('content'),
                "reasoning_details": message.get('reasoning_details') or "GPT-OSS-120B reasoning complete."
            }
        except Exception as e:
            return self._get_fallback(f"OpenRouter Error: {e}")

    def _get_fallback(self, error_msg: str) -> Dict[str, Any]:
        print(f"LLMService Fallback: {error_msg}")
        return {
            "content": "Based on your profile, you are a strong candidate for several benefits. Please ensure your Aadhaar is linked to your current mobile number for a seamless application process.",
            "reasoning_details": f"Note: AI is in fallback mode ({error_msg[:20]}...). Matching pre-indexed profile data."
        }

    def _offline_response(self, messages: List[Dict[str, Any]]) -> Dict[str, Any]:
        latest = ""
        if messages:
            latest = str(messages[-1].get("content", "")).strip()
        if latest:
            summary = (
                "Offline mode is active. Here is a local rule-based explanation: "
                "you may qualify based on your profile and scheme criteria. "
                "Review required documents and submit details carefully."
            )
        else:
            summary = (
                "Offline mode is active. Local rules are being used to explain scheme eligibility."
            )
        return {
            "content": summary,
            "reasoning_details": "LLM_MODE=offline. No external API calls were made."
        }

    async def generate_text(self, prompt: str) -> str:
        messages = [{"role": "user", "content": prompt}]
        result = await self.generate_with_reasoning(messages)
        return result["content"]

# Singleton
llm_service = LLMService()
